#!/bin/sh
### BEGIN INIT INFO
# Provides:          astrobox
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 3 4 5 6
# Short-Description: AstroBox
# Description:       Printer Controller Host
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
PIDFILE=/var/run/astrobox.pid
ENABLED=1

if [ -e /etc/default/astrobox ]; then
  . /etc/default/astrobox
fi

test "$ENABLED" != "0" || exit 0

[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions

astrobox_start()
{
  python -OO /AstroBox/run --config /etc/astrobox/config.yaml --host 127.0.0.1 --daemon start --pid "$PIDFILE" || return 2
  return 0
}

astrobox_stop()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return 0
  fi

  python -OO /AstroBox/run --daemon stop --config /etc/astrobox/config.yaml --host 127.0.0.1 --pid "$PIDFILE" || return 2
}

astrobox_restart()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return astrobox_start
  fi

  python -OO /AstroBox/run --daemon restart --config /etc/astrobox/config.yaml --host 127.0.0.1 --pid "$PIDFILE" || return 2
}

astrobox_status()
{
  if [ ! -f $PIDFILE ] ; then
    # program not running
    return 3
  fi

  for pid in $(cat $PIDFILE) ; do
    if ! ps --no-headers p "$pid" | grep astrobox > /dev/null ; then
      # program running, bogus pidfile
      return 1
    fi
  done

  return 0
}


case "$1" in
start)
  log_daemon_msg "Starting astrobox" "astrobox"

# NOT READY YET, DO IT MANUALLY
#  if [ ! -f /etc/astrobox/fs_expanded ]; then
#		if [ -f /etc/os-release ]; then
#			. /etc/os-release
#
#			echo $ID
#			if [ "raspbian" == "$ID" ]; then # Raspberry PI
#				raspi-config --expand-rootfs
#			else # Other platforms (tested on BBB - Debian)
#				/etc/astrobox/resizePartition.sh
#			fi
#    fi
#    
#    echo "1" > /etc/astrobox/fs_expanded
#  fi
#	resize2fs /dev/$(lsblk -o name,mountpoint,label,size,uuid | grep rootfs | cut -b 7- | cut -d ' ' -f1)

  if [ ! -f /etc/astrobox/box-id ]; then
    if [ ! -f /etc/astrobox/default-hostname ]; then
      log_daemon_msg "Setting initial hostname..." "astrobox"
      python -OO /AstroBox/set-initial-hostname -c /etc/astrobox/config.yaml

      log_daemon_msg "Executing first-time boot scripts" "astrobox"

      if [ -d /etc/astrobox/initial-scripts ]; then
        for f in /etc/astrobox/initial-scripts/*
        do
          if [ -x "$f" ]; then
            log_daemon_msg "Executing $f..." "astrobox"
            $f
          fi
        done
      fi

      log_daemon_msg "Rebooting..." "astrobox"
      reboot
      exit 0
    fi
  fi

  MAX_NETWORK_RETRIES=10
  WAIT_BETWEEN_NETWORK_RETRIES=2
  PING_HOST=8.8.8.8
  NETWORK=0

  for i in `seq 1 $MAX_NETWORK_RETRIES`
  do
          if ping -W 2 -c 1 $PING_HOST > /dev/null 2>&1 ; then
                  NETWORK=1
                  break
          fi
          sleep $WAIT_BETWEEN_NETWORK_RETRIES
  done

  if [ $NETWORK = 0 ]; then
    service wifi_access_point start > /dev/null 2>&1
  fi

  /usr/local/sbin/astrobox-init
  astrobox_start
  ret=$?
  case "$ret" in
  0)
    log_end_msg 0
    ;;
  1)
    log_end_msg 1
    echo "pid file '$PIDFILE' found, astrobox not started."
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  exit $ret
  ;;
stop)
  log_daemon_msg "Stopping astrobox" "astrobox"
  astrobox_stop
  ret=$?
  case "$ret" in
  0|1)
    log_end_msg 0
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  exit $ret
  ;;
restart)
  log_daemon_msg "Restarting astrobox" "astrobox"
  astrobox_restart
  case "$?" in
  0)
    log_end_msg 0
    ;;
  1)
    log_end_msg 1
    ;;
  2)
    log_end_msg 1
    ;;
  esac
  ;;
status)
  astrobox_status
  ret=$?
  case "$ret" in
  0)
    echo "astrobox is running."
    ;;
  1)
    echo "astrobox dead, but $PIDFILE exists."
    ;;
  *)
    echo "astrobox not running."
    ;;
  esac
  exit $ret
  ;;
*)
  echo "Usage: /etc/init.d/astrobox {start|stop|restart|status}"
  exit 2
  ;;
esac

:
